version: "3.8"
services:
  react_frontend:
    build: ./frontend
    container_name: react_frontend
    ports: 
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules
    stdin_open: true
    tty: true




